services:
  # Backend API Service
  - type: web
    name: student-dropout-api
    env: python
    plan: starter
    pythonVersion: 3.11.9
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: 1
    healthCheckPath: /docs

  # Frontend Service
  - type: web
    name: student-dropout-frontend
    env: static
    plan: starter
    buildCommand: |
      cd frontend
      npm install --production
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://student-dropout-api.onrender.com
